config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :items, only: [:new, :show, :index, :destroy, :create, :update, :edit] do
    member do
      get :color
    end
  end
   get '/wardrobe', to: 'pages#wardrobe'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  # the picture the user takes when scanning a clothing item.
  # use item.image.attached? to check for an image
  validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

def default_url_options
  { host: ENV["www.infitter.net"] || "localhost:3000" }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # added this skipping to spare some logging in during developement, this needs to go later.
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  include Pagy::Backend

  def index
    # added a sorting to make sure the most recently added items are displayed first .sort_by { |item| item.created_at }
    @items = current_user.items
    @items = @items.order(:created_at)
    @colors = @items.select(:color).pluck(:color).uniq
    @favorite_colors = @items.where(favorite:true).select(:color).pluck(:color).uniq

    if params[:favorite]
      @items = @items.where(favorite:true)
    end

    if params[:category]
      @category = Category.find_by_name(params[:category])
      @items = @items.where(category:@category)
    end

    @color = params[:color]
    if @color
      @items = @items.where(color:@color)
    end

    @pagy, @records = pagy(@items, link_extra: "data-remote ='true'")
    @item = @records.last
  end

  def show

    # if params[:color]
    #   @color = params[:color]
    #   category = Category.find_by_name(params[:category])
    #   @item = Item.where(color:@color, category:category)
    # end
    if params.has_key?(:outfit)
      @index = params[:index].to_i
      @outfit = params[:outfit].map { |id| Item.find(id)}
      @item = @outfit[@index]
    else
      @item = Item.find(params[:id])
      @outfit ? nil : @outfit = top_secret_matching_algorithm(@item)
      @index = @outfit.index(@item)
    end
    @ids = @outfit.map { |item|  item.id}
    @next = @index >= 3 ? 0 : @index + 1
    @prev = @index <= 0 ? 3 : @index - 1
    @previous_color = params[:color]


  end

  def destroy
    @article = Item.find(params[:id])
    @article.destroy

    redirect_to items_path
  end


  def new
    @colors = current_user.items.limit(9).pluck(:color)
    @new_item = current_user.items.new
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def update
    @item = current_user.items.find(params[:id])
    @item.update!(item_params)
    # will return to this later, see about adding an id and anchoring to it
    redirect_to items_path(category:@item.category.name, color:@item.color)
  end

  def create
    @new_item = current_user.items.new(item_params)
    @new_item.user = current_user
    @new_item.category = Category.find_by_name(category_param)
    if @new_item.save!
      redirect_to item_path(@new_item)
    else
      @colors = Item.limit(9).pluck(:color)
      render :new
    end
  end

  def color
    @item = current_user.items.find(params[:id])
  end

  private

  def top_secret_matching_algorithm(item)
    tops = Item.where(category:Category.find_by_name("tops"))
    bottoms = Item.where(category:Category.find_by_name("bottoms"))
    shoes = Item.where(category:Category.find_by_name("shoes"))
    accessories = Item.where(category:Category.find_by_name("accessories"))
    array = []
    top = tops.sample
    bottom = bottoms.sample
    shoe = shoes.sample
    acessory = accessories.sample
    [acessory, top, bottom, shoe].map do |i|
      i.category == item.category ? array << item : array << i
    end
    array
  end

# def top_secret_matching_algorithm(item)
#     tops = Item.find_by(category:Category.find_by_name("tops"))
#     bottoms = Item.find_by(category:Category.find_by_name("bottoms"))
#     shoes = Item.find_by(category:Category.find_by_name("shoes"))
#     accessories = Item.find_by(category:Category.find_by_name("accessories"))
#     array = [accessories, tops, bottoms, shoes]
#     carousel = []
#     [accessories, tops, bottoms, shoes].map do |i|
#       i.category == item.category ? carousel << item : carousel << i
#     end
#     array << item
#     raise
#   end
  def item_params
    params.require(:item).permit(:color, :image, :favorite, :name)
  end


  def category_param
    params.require(:item)[:category]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end


  def wardrobe
    @item = Item.last
    if params[:color]
      @color = params[:color]
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
   include Pagy::Frontend
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/items/_carousel.html.erb
<!--  see components/_backgrounds.scss for the rules for this container  -->

<% if @previous_color %>
  <div class="container-adaptive" id="container-adaptive" style="background: <%= @previous_color %>">
<% else %>
  <div class="container-adaptive" id="container-adaptive" style="background: <%= @item.color %>">
<% end %>
<!--   rules for this heart is in _heart.scss -->
<% if @previous_color %>
  <div class="hidden" id="previous_color" data-url="<%= @item.color %>" style="background-color: <%= @previous_color %>"></div>
<% end %>

  <div class= "item-card">
    <% if @item.favorite? %>
      <%= simple_form_for @item do |f| %>
        <%= f.input :favorite, :input_html => { :checked => false, class: "hidden" }, label: false  %>
        <%= button_tag class: "knapp", style: "background-color: transparent", type: 'submit' do %>
          <i class="heart fas fa-heart heartbutton" aria-hidden="true" style="background-color: transparent" ></i>
        <% end %>
      <% end %>
    <% else %>
      <%= simple_form_for @item do |f| %>
        <%= f.input :favorite, :input_html => { :checked => true, class: "hidden"}, label: false %>
        <%= button_tag class: "knapp", style: "background-color: transparent", type: 'submit' do %>
          <i class="heart far fa-heart heartbutton" aria-hidden="true" style="background-color: transparent" ></i>
        <% end %>
      <% end %>
    <% end %>
    <div>
    </div>
    <%= image_tag @item.image, class: "image-carousel"%>

      <%=link_to item_path(@item, index:@next, outfit:@ids, color:@item.color) do %>
        <%= image_tag @outfit[@next].image, class: "image-carousel front"%>
      <% end %>


      <%= link_to item_path(@item, index:@prev, outfit:@ids, color:@item.color) do %>
        <%= image_tag @outfit[@prev].image, class: "image-carousel shadow"%>
      <% end %>

  </div>
  <div>
  </div>
  <div>

  </div>
<button class="las la-trash-alt fa-3x trashcan" data-toggle="modal" data-target="#exampleModal"></button>
    <%= render "shared/modal" %>

</div>

app/views/items/_categories.html.erb
<div class="wrapper-wardrobe" style="background-color: <%= @color %>">
  <h2>Wardrobe</h2>
    <div class="cards-wardrobe">

      <div class="color-ellipse" >
        <% if @items.joins(:category).where(categories:{name:"shoes"}).exists? %>
        <%= link_to items_path(category:"shoes", color:@color),class: "no-underline" do %>
          <%=image_tag("icons/icon_shoe.png", class: "icon_shoes")%>
        <% end %>
        <% else %>
          <%=image_tag("icons/icon_shoe.png", class: "icon_shoes")%>
        <% end %>
      </div>

      <div class="color-ellipse">
        <% if @items.joins(:category).where(categories:{name:"tops"}).exists? %>
        <%= link_to items_path(category:"tops", color:@color),class: "no-underline" do %>
          <%=image_tag("icons/icon_top.png", class: "icon_top")%>
        <% end %>
        <% else %>
          <%=image_tag("icons/icon_top.png", class: "icon_top")%>
        <% end %>
      </div>

      <div class="color-ellipse">
         <% if @items.joins(:category).where(categories:{name:"accessories"}).exists? %>
        <%= link_to items_path(category:"accessories", color:@color),class: "no-underline" do %>
          <%=image_tag("icons/icon_cap.png", class: "icon_accessory")%>
        <% end %>
        <% else %>
          <%=image_tag("icons/icon_cap.png", class: "icon_accessory")%>
        <% end %>
      </div>

       <div class="color-ellipse">
        <% if @items.joins(:category).where(categories:{name:"bottoms"}).exists? %>
        <%= link_to items_path(category:"bottoms", color:@color),class: "no-underline" do %>
        <%=image_tag("icons/icon_pants.png", class: "icon_bottom")%>
        <% end %>
        <% else %>
        <%=image_tag("icons/icon_pants.png", class: "icon_bottom")%>
        <% end %>
      </div>
    </div>
</div>

app/views/items/_category_selection.html.erb
<div class="wrapper-category">
  <h2>Choose category</h2>
  <div class="cards-category">
      <button style="background-color:item[color]" class="button-category"  name="item[category]" value="shoes">
      <div class="super-box" style="background-color:item[color]">
        <div class="clr-ellipse">
          <%=image_tag("icons/icon_shoe.png", class: "icon_shoes")%>
        </div>
        <div class="text-category">
          <h2>Shoes</h2>
        </div>
     </div>
      </button>


      <button style="background-color:item[color]" class="button-category" name="item[category]" value="tops">
      <div class="super-box" style="background-color:item[color]">
        <div class="clr-ellipse">
          <%=image_tag("icons/icon_top.png", class: "icon_top")%>
        </div>
        <div class="text-category">
          <h2>Tops</h2>
        </div>
      </div>
      </button>


      <button style="background-color:item[color]" class="button-category" name="item[category]" value="accessories">
      <div class="super-box" style="background-color:item[color]">
        <div class="clr-ellipse">
          <%=image_tag("icons/icon_cap.png", class: "icon_accessory")%>
        </div>
        <div class="text-category">
          <h2>Accessories</h2>
        </div>
     </div>
     </button>

     <button style="background-color:item[color]" class="button-category" name="item[category]" value="bottoms">
      <div class="super-box" style="background-color:item[color]">
        <div class="clr-ellipse">
          <%=image_tag("icons/icon_pants.png", class: "icon_bottom")%>
        </div>
        <div class="text-category">
          <h2>Bottoms</h2>
        </div>
      </div>
     </button>
  </div>
</div>

app/views/items/_colors.html.erb
<div class= "container-gray">
  <h2 id="mycolors">My colors</h2>
  <div class="" role="navigation">
    <ul class="nav nav-tabs bar" id="myTab" role="tablist">
      <!-- note the use of bootstrap classes for spacing -->
      <li class="nav-item mx-3 mt-1">
      <a class="nav-link active clrtabs" id="recent-tab" data-toggle="tab" href="#recent" role="tab" aria-controls="recent" aria-selected="true">Recent</a>
      </li>
      <li class="nav-item mx-3 mt-1">
        <a class="nav-link clrtabs" id="favorite-tab" data-toggle="tab" href="#favorite" role="tab" aria-controls="favorite" aria-selected="false">Favorite</a>
      </li>
    </ul>
<!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="recent" role="tabpanel" aria-labelledby="recent-tab">
      <div class="items-index">
          <% @colors.each do |color| %>
      <%= link_to items_path(color:color), class: "no-underline" do %>
        <div class="color" style="background-color: <%=color%>">
          <% if Item.where(color:color, favorite:true).exists? %>
            <i class="heart fas fa-heart"></i>
          <% else  %>
            <i class="heart far fa-heart"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
    </div>
    <div class="tab-pane" id="favorite" role="tabpanel" aria-labelledby="favorite-tab">
      <div class="items-index">
          <% @favorite_colors.each do |color| %>
      <%= link_to items_path(color:color), class: "no-underline" do %>
        <div class="color" style="background-color: <%=color%>">
          <% if Item.where(color:color, favorite:true).exists? %>
            <i class="heart fas fa-heart"></i>
          <% else  %>
            <i class="heart far fa-heart"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
    </div>
  </div>
</div>
</div>

<!-- <div class="hidden new-item-form"><%= render "shared/item_form" %></div> -->

app/views/items/_outfit.html.erb
<div class="outfit">

  <div class="container-adaptive" id="component1" style="background-color: <%= @outfit[0].color %>">
<!--     <% if @outfit[0].favorite %>
      <i class="heart fas fa-heart"></i>
    <% else %>
      <i class="heart far fa-heart"></i>
    <% end %> -->
        <div class= "item-card">
    <div class="item-circle" style= "background-color: <%= @outfit[0].color %>">
      <% if @outfit[0].name %>
        <p><%= @outfit[0].name %></p>
      <% else %>
      <p>A name is missing for this item</p>
      <% end %>
    </div>
    <%= image_tag @outfit[0].image, class: "image-carousel"%>
  </div>
  </div>


  <div class="container-adaptive" id="component2" dir="ltr" style="background-color: <%= @outfit[1].color %>">
<!--     <% if @outfit[1].favorite %>
      <i class="heart fas fa-heart"></i>
    <% else %>
      <i class="heart far fa-heart"></i>
    <% end %> -->
        <div class= "item-card">
    <div class="item-circle" style=" background-color: <%= @outfit[1].color %>">
      <% if @outfit[1].name %>
        <p><%= @outfit[1].name %></p>
      <% else %>
      <p>A name is missing for this item</p>
      <% end %>
    </div>
    <%= image_tag @outfit[1].image, class: "image-carousel"%>
  </div>
  </div>


  <div class="container-adaptive" id="component3" style="background-color: <%= @outfit[2].color %>">
<!--     <% if @outfit[2].favorite %>
      <i class="heart fas fa-heart"></i>
    <% else %>
      <i class="heart far fa-heart"></i>
    <% end %> -->
        <div class= "item-card">
    <div class="item-circle" style=" background-color: <%= @outfit[2].color %>">
      <% if @outfit[2].name %>
        <p><%= @outfit[2].name %></p>
      <% else %>
      <p>A name is missing for this item</p>
      <% end %>

    </div>
    <%= image_tag @outfit[2].image, class: "image-carousel"%>
  </div>
  </div>



  <div class="container-adaptive" id="component4" dir="ltr" style="background-color: <%= @outfit[3].color %>">
<!--     <% if @outfit[3].favorite %>
      <i class="heart fas fa-heart"></i>
    <% else %>
      <i class="heart far fa-heart"></i>
    <% end %> -->
    <div class= "item-card">
    <div class="item-circle" style=" background-color: <%= @outfit[3].color %>">
      <div class="outfit-text">
      <% if @outfit[3].name %>
        <p><%= @outfit[3].name %></p>
      <% else %>
      <p>A name is missing for this item</p>
      <% end %>
      </div>
    </div>
    <%= image_tag @outfit[3].image, class: "image-carousel"%>
  </div>
  </div>

</div>

app/views/items/index.html.erb
<% if @category %>
  <%= render "shared/scroll_page"  %>
<% elsif @color %>
  <%= render "shared/scroll_page" %>
<% else %>
  <%= render "shared/start_index" %>
<% end %>

app/views/items/new.html.erb
<%= render "shared/item_form" %>

app/views/items/show.html.erb
<% if @outfit %>
  <%= render "carousel"  %>
<% else %>
  <!-- see components/_backgrounds.scss for the rules for this container-->
  <div class="container-adaptive" style="background-color: <%= @item.color %>">
    <!-- rules for this heart is in _heart.scss -->
    <% if @item.favorite %>
      <i class="heart fas fa-heart"></i>
    <% else %>
      <i class="heart far fa-heart"></i>
    <% end %>
    <%= image_tag @item.image, class: "image-item"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- line of code below was added to prevent ui flickering on carousel because of turbolinks caching
    for more information see: https://stackoverflow.com/questions/39864617/rails-turbolinks-5-causing-causing-ui-flicker
    -Eirik -->
    <meta name="turbolinks-cache-control" content="no-cache">

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- plus font symbol -->
    <script defer src="https://friconix.com/cdn/friconix.js"> </script>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">


  </head>

  <body style="background-color: #3C3A3A;">
    <div>
      <%= render 'shared/flashes' %>

      <main id="main-content">
        <div class="page-content"><%= yield %></div>
        <div class="hidden new-item-form"><%= render "shared/item_form" %></div>
      </main>
      <%= render "shared/navbar"  unless request.path == "/users/sign_up"  %>
    </div>
  </body>
<!-- window.location -->
</html>

app/views/pages/category.html.erb
<div class="wrapper-category">
  <h2>Before we find your match - what category is this item?</h2>
  <div class="cards-category">

      <div class="super-box">
        <div class="clr-ellipse" style="background-color: <% @item.color %>">
          <i class="fas fa-tshirt fa-3x"></i>
        </div>
        <div class="text-category">
          <h2>Shoes</h2>
        </div>
     </div>

      <div class="super-box">
        <div class="clr-ellipse">
            <i class="fas fa-tshirt fa-3x"></i>

        </div>
        <div class="text-category">
          <h2>Top</h2>
        </div>
      </div>

      <div class="super-box">
        <div class="clr-ellipse">
          <i class="fas fa-tshirt fa-3x"></i>
        </div>
        <div class="text-category">
          <h2>Accessory</h2>
        </div>
     </div>

      <div class="super-box">
        <div class="clr-ellipse">
          <i class="fas fa-tshirt fa-3x"></i>
        </div>
        <div class="text-category">
          <h2>Bottom</h2>
      </div>
    </div>
  </div>
</div>

app/views/pages/wardrobe.html.erb
<div class="wrapper-wardrobe" style="background-color: <%= @color %>">
  <h2>Wardrobe</h2>
    <div class="cards-wardrobe">
      <% @item.color %>
      <div class="color-ellipse" >
        <% @item.color %>
          <%=image_tag("icons/icon_shoe.png", class: "icon_shoes")%>
      </div>
      <div class="color-ellipse">
        <%= link_to items_path(category:"tops", color:@color) class: "no-underline"  do %>
          <%=image_tag("icons/icon_top.png", class: "icon_top"),%>
        <% end %>
      </div>
       <div class="color-ellipse">
        <%= link_to items_path(category:"shoes")do %>
          <%=image_tag("icons/icon_cap.png", class: "icon_accessory")%>
        <% end %>
      </div>
      <div class="color-ellipse">
        <%=image_tag("icons/icon_pants.png", class: "icon_bottom")%>
      </div>
    </div>
</div>

app/views/shared/_carousel_old.html.erb
_carousel_old.html.erb
<!-- Please note that this is just to keep the code for the old carousel for future reference -->

<!--  see components/_backgrounds.scss for the rules for this container  -->
<div class="container-adaptive" style="background-color: <%= @item.color %>">
<!--   rules for this heart is in _heart.scss -->


  <div class= "item-card">
    <% if @item.favorite? %>
      <%= simple_form_for @item do |f| %>
        <%= f.input :favorite, :input_html => { :checked => false, class: "hidden" }, label: false  %>
        <%= button_tag class: "knapp", style: "background-color: #{@item.color}", type: 'submit' do %>
          <i class="heart fas fa-heart heartbutton" aria-hidden="true" style="background-color: <%= @item.color %>" ></i>
        <% end %>
      <% end %>
    <% else %>
      <%= simple_form_for @item do |f| %>
        <%= f.input :favorite, :input_html => { :checked => true, class: "hidden"}, label: false %>
        <%= button_tag class: "knapp", style: "background-color: #{@item.color}", type: 'submit' do %>
          <i class="heart far fa-heart heartbutton" aria-hidden="true" style="background-color: <%= @item.color %>" ></i>
        <% end %>
      <% end %>
    <% end %>
    <div>
      <div class="outfit-text">
        <% if @item.name %>
          <%=  link_to "Create outfit", item_path(@item), class: "no-underline item-circle", style:" background-color: #{@item.color}" %>
        <% else %>
          <%=  link_to "Create outfit with this item #{@item.name}", item_path(@item), class: "no-underline item-circle", style:" background-color: #{@item.color}" %>
        <% end %>
      </div>
    </div>
    <%= image_tag @item.image, class: "image-carousel"%>
    <% if pagy_prev_url(@pagy) %>
      <%=link_to pagy_prev_url(@pagy) do %>
        <%= image_tag @items.first.image, class: "image-carousel front"%>
      <% end %>
    <% end %>
    <% if pagy_next_url(@pagy) %>
      <%=link_to pagy_next_url(@pagy) do %>
        <%= image_tag @items.last.image, class: "image-carousel shadow"%>
      <% end %>
    <% end %>
  </div>
  <div>
  </div>
  <div>
<!--     <% if pagy_prev_url(@pagy) %>
      <%= link_to "<", pagy_prev_url(@pagy) %>
    <% end %> -->
<!--     <% if pagy_next_url(@pagy) %>
      <%= link_to ">", pagy_next_url(@pagy) %>
    <% end %> -->

  </div>
<button class="las la-trash-alt fa-3x trashcan" data-toggle="modal" data-target="#exampleModal"></button>
    <%= render "shared/modal" %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_item_form.html.erb
<div class="container pt-1">
  <div class="form-wrapper pt-5">
    <%= simple_form_for @new_item || Item.new, remote: false do |f| %>

      <div class="step1" id="step1">
          <%= f.file_field :image, accept: "image/*", capture: "camera", id: "camera"  %>

          <div class="color-picker-wrapper hidden">
            <div class="text-colorsfound">
              <h2 class="color-match">Are any of these colors a match?</h2>
            </div>
          <div class="color-picker">
            <div class="cards">
            </div>
            <div class="btns-pick">
            <button id="pick-category" class="hidden button-rectangle btn" type="button">Match</button>
            </div>
            <div class="btns-pick">
            <button id="pick-again" class="hidden button-rectangle btn" type="button">Retake</button>
            </div>
          </div>
          <div class="guide-text">
          </div>
        </div>
      </div>
      <div class="step2 hidden" id="step2">
        <%= render "items/category_selection" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" >
  <div class="modal-dialog" role="document">
    <div class="popup-content">
      <div class="modal-header">
        <h2 class="popup-title">Are you sure?</h2>
        <button class="close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-footer">
        <div>
          <button class="button-rectangle" data-dismiss="modal">Cancel</button>
        </div>
        <div>
          <%= link_to item_path(@item),
          method: :delete do %>
            <button class="button-rectangle">Delete</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-infitter">
  <div class="nav-wrapper">
  <!-- this conditonal makes sure the home button is not rendered if the user is
  currently on the home page -->
    <% if request.path != "/" && request.path != "/users/sign_in" %>
      <div class="classguy">
        <%= link_to new_item_path, class: "camera-button", id:"camera-link" do %>
          <i class="fas fa-camera fa-2x" id="cam-btn"></i>
        <% end %>
      </div>
    <% end %>
    <ul class="mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <p><%= link_to "My wardrobe", items_path, class: "nav-link" %></p>
        </li>

        <li class="nav-item">
            <p><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"  %></p>
        </li>
      </ul>
      <% else %>
        <li class="nav-item">


            <p><%= link_to "Log in", new_user_session_path, class: "nav-home"%></p>

        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/ui_kit/_buttons.html.erb
<div class="button-rectangle">
  Wrong color. Pick again!
</div>

<div class="camera-button">
  <i class="fas fa-camera fa-2x "></i>
</div>

app/views/ui_kit/_hearts.html.erb
<!-- solid heart, used for items where favourite is true -->
<i class="heart fas fa-heart"></i>

<!-- empty heart, used for items where favourite is false -->

<i class="heart far fa-heart"></i>